from pathlib import Path
p=Path('index.html')
s=p.read_text()
old='''          {adminFunnel && (\n            <div style={{ marginBottom: 16, padding: 16, borderRadius: 16, background: "rgba(255,255,255,0.82)", border: "1px solid #F0D5DB" }}>\n              <div style={{ fontSize: 12, fontWeight: 900, color: "#4C8FE8" }}>🚦 ONBOARDING FUNNEL</div>\n              <div style={{ marginTop: 4, fontSize: 10.5, color: "#8C6B9E" }}>How many distinct accounts reached each onboarding step, versus how many finished.</div>\n              <div style={{ display: "grid", gap: 6, marginTop: 10 }}>\n                {(adminFunnel.by_step || []).map((row) => {\n                  const started = adminFunnel.started || 1;\n                  const pct = Math.round((row.reached / started) * 100);'''
new='''          {adminFunnel && (\n            <div style={{ marginBottom: 16, padding: 16, borderRadius: 16, background: "rgba(255,255,255,0.82)", border: "1px solid #F0D5DB" }}>\n              <div style={{ fontSize: 12, fontWeight: 900, color: "#4C8FE8" }}>🚦 ONBOARDING FUNNEL</div>\n              <div style={{ marginTop: 4, fontSize: 10.5, color: "#8C6B9E", lineHeight: 1.45 }}>Shows how many tracked accounts reached each stage and where people stopped. Cozy and Guardian onboarding are combined here, so stage names are intentionally broad.</div>\n              <div style={{ marginTop: 8, padding: "8px 10px", borderRadius: 10, background: "#F7FBFF", border: "1px solid #DCEEFF", fontSize: 10.5, color: "#6B5A7D" }}>\n                <b>{adminFunnel.started || 0}</b> tracked starters · <b>{adminFunnel.completed || 0}</b> finished · <b>{Math.max(0, (adminFunnel.started || 0) - (adminFunnel.completed || 0))}</b> unfinished\n              </div>\n              <div style={{ display: "grid", gap: 9, marginTop: 10 }}>\n                {(adminFunnel.by_step || []).map((row, index, rows) => {\n                  const started = adminFunnel.started || 1;\n                  const pct = Math.round((row.reached / started) * 100);\n                  const nextReached = index < rows.length - 1 ? Number(rows[index + 1]?.reached || 0) : Number(adminFunnel.completed || 0);\n                  const dropped = Math.max(0, Number(row.reached || 0) - nextReached);\n                  const stageNames = ["Profile & welcome", "Setup choices", "Starting point", "Goals & support", "Preferences", "Ready to begin"];\n                  const stageName = stageNames[Math.max(0, Number(row.step || 1) - 1)] || `Stage ${row.step}`;'''
if old not in s: raise SystemExit('funnel header block not found')
s=s.replace(old,new,1)
old2='''                        <span>Step {row.step}</span>\n                        <span>{row.reached} ({pct}%)</span>'''
new2='''                        <span><b>{stageName}</b> <span style={{ fontSize: 9.5, color: "#9A86A7" }}>· Step {row.step}</span></span>\n                        <span>{row.reached} reached · {pct}%</span>'''
if old2 not in s: raise SystemExit('funnel row label block not found')
s=s.replace(old2,new2,1)
old3='''                      <div style={{ height: 8, borderRadius: 5, background: "#EAF4FF", overflow: "hidden" }}>\n                        <div style={{ height: "100%", width: `${pct}%`, background: "#4C8FE8", borderRadius: 5 }} />\n                      </div>'''
new3='''                      <div style={{ height: 8, borderRadius: 5, background: "#EAF4FF", overflow: "hidden" }}>\n                        <div style={{ height: "100%", width: `${pct}%`, background: "#4C8FE8", borderRadius: 5 }} />\n                      </div>\n                      <div style={{ marginTop: 3, fontSize: 9.8, color: dropped > 0 ? "#B06A7A" : "#7B9B8F" }}>{dropped > 0 ? `${dropped} stopped here before the next stage` : "No drop-off at this stage"}</div>'''
if old3 not in s: raise SystemExit('funnel bar block not found')
s=s.replace(old3,new3,1)
p.write_text(s)
